### ISSUE TITLE
Support for Gradle 7.0?

### ISSUE THREAD

**Issue by ndw** [cdsap/Talaiot#288] opened 2021-04-20 08:03 UTC
I get the following deprecation warning with 1.4.2:

> The BuildListener.buildStarted(Gradle) method has been deprecated. This is scheduled to be removed in Gradle 7.0. Consult the upgrading guide for further information:
>https://docs.gradle.org/6.7/userguide/upgrading_version_5.html#apis_buildlistener_buildstarted_and_gradle_buildstarted_have_been_deprecated

Are there any plans to make the plugin work with Gradle 7?

**Comment by cdsap** [comment] 2021-04-20 16:46
Hi @ndw, thanks for the report, I will check it today

**Comment by cdsap** [comment] 2021-04-21 14:12
PR created

**Comment by cdsap** [comment] 2021-04-29 13:51
Hi, version 1.5.0 has been released supporting Gradle 7. 
We have migrated to Sonatype. The plugin id is:
```
plugins {
  id("io.github.cdsap.talaiot") version "1.5.0"
}
```

**Comment by ndw** [comment] 2021-04-29 17:01
I've switched to 1.5.0:
```
plugins {
  id "java"
  id "maven-publish"
  id "signing"
  id "io.github.cdsap.talaiot" version "1.5.0"
}
```
with this configuration:
```
talaiot {
  metrics {
    performanceMetrics = false
  }
  publishers {
    taskDependencyGraphPublisher {
      gexf = false
      dot = true
      html = false
    }
  }
}
```
and I'm still getting this warning:

> Configure project :
> The BuildListener.buildStarted(Gradle) method has been deprecated. This is scheduled to be removed in Gradle 7.0. Consult > the upgrading guide for further information: > https://docs.gradle.org/6.7/userguide/upgrading_version_5.html#apis_buildlistener_buildstarted_and_gradle_buildstarted_have_been_deprecated

It doesn't occur if I remove the `talaiot` plugin.

User error?

**Comment by cdsap** [comment] 2021-04-30 02:24
hi @ndw thanks again for testing it. 
I tested different scenarios for a simple project using:
```
plugins {
  id "io.github.cdsap.talaiot" version "1.5.0"
}
```
* Gradle 6.7
Build execution ok. No warnings
<img width="425" alt="Screen Shot 2021-04-29 at 7 15 46 PM" src="https://user-images.githubusercontent.com/475733/116640454-82e41c80-a91f-11eb-94f2-490229bfb5ad.png">
<img width="449" alt="Screen Shot 2021-04-29 at 7 15 58 PM" src="https://user-images.githubusercontent.com/475733/116640465-8d061b00-a91f-11eb-89c4-aaaf0df210ad.png">

* Gradle 6.8.3
Build execution ok. No warnings
<img width="479" alt="Screen Shot 2021-04-29 at 6 58 31 PM" src="https://user-images.githubusercontent.com/475733/116640564-be7ee680-a91f-11eb-8201-de9f1b3f21aa.png">
<img width="452" alt="Screen Shot 2021-04-29 at 7 00 08 PM" src="https://user-images.githubusercontent.com/475733/116640568-bfb01380-a91f-11eb-82db-4415693ed1dc.png">

* Gradle 7
Build execution ok. No warnings
<img width="478" alt="Screen Shot 2021-04-29 at 6 59 56 PM" src="https://user-images.githubusercontent.com/475733/116640557-b9ba3280-a91f-11eb-80c5-11ffc8b2c894.png">
<img width="460" alt="Screen Shot 2021-04-29 at 6 58 47 PM" src="https://user-images.githubusercontent.com/475733/116640576-c3dc3100-a91f-11eb-9b45-210370b5c1de.png">

There are other plugins involved? But you mentioned if you remove the plugin it works. I would need more data, Could be possible get the complete log of:

> Configure project :
> The BuildListener.buildStarted(Gradle) method has been deprecated. This is scheduled to be removed in Gradle 7.0. Consult > the upgrading guide for further information: > https://docs.gradle.org/6.7/userguide/upgrading_version_5.html#apis_buildlistener_buildstarted_and_gradle_buildstarted_have_been_deprecated
> 

Thanks

**Comment by ndw** [comment] 2021-04-30 09:22
I'm quite confused by the different results that we're seeing. Here's my `build.gradle` file:
```gradle
plugins {
  id "io.github.cdsap.talaiot" version "1.5.0"
}

// Testing task for various Gradle debugging efforts
task helloWorld() {
  doLast {
    println("Hello, world.")
  }
}
```
And here's the output I get:
```
$ ./gradlew helloWorld

> Configure project :
The BuildListener.buildStarted(Gradle) method has been deprecated. This is scheduled to be removed in Gradle 7.0. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#apis_buildlistener_buildstarted_and_gradle_buildstarted_have_been_deprecated

> Task :helloWorld
Hello, world.
```
I've put the debug log in [a gist](https://gist.github.com/ndw/b346ff5a45277a26b745f28dc2a0740e).

**Comment by cdsap** [comment] 2021-05-02 03:09
Thanks for the gist and example. I reproduced it with Gradle 6.5. I was confused too, I added integration tests for Gradle 7 and tested with Gradle 7 projects. 
The problem comes from the origin of the build deprecation message. `TalaiotListener` is implementing https://github.com/gradle/gradle/blob/fe98989182eddc66d20ee7fea82c1532287d5090/subprojects/core-api/src/main/java/org/gradle/internal/InternalBuildListener.java  

This interface allows us to be compatible with the current contract of `BuildListener`. Before Gradle 7, the implementation was:
```
public interface InternalBuildListener extends BuildListener, InternalListener {
    /**
     * <p>Called when the build is started.</p>
     *
     * @param gradle The build which is being started. Never null.
     */
    @SuppressWarnings("deprecation")
    void buildStarted(Gradle gradle);
}
```
That's why you can see the build deprecation message in Gradle 6.x versions.  You shouldn't have problems updating to Gradle 7 because the change on the interface in the Gradle API.

I reopened the issue again, to be sure that works properly.

**Comment by cdsap** [comment] 2021-07-13 19:31
since we have worked with Gradle 7 in the project I'm closing this issue.

**Closed by cdsap** 2021-07-13 19:31 UTC
